### ISSUE TITLE
Improvements to the golden UI tester

### ISSUE THREAD

**Issue by fmease** [fmease/lushui#140]
- [x] do not print the list of used filters after the stats: they are quite useless tbh
- [x] if there are any test failures or invalid tests, print a list of all failing tests and one of all invalid ones, respectively, more concretely their full path relative to the current directory to enable people to quickly copy the paths and open the test files
- [x] replace loose and exact filters with taking any number of files and folders as argument.
      shell globbing and autocompletion are going to make the UX great
- [x] (maybe) make “TEST fail check” the default rendering explicit test configurations optional
- [x] make the test configuration language more flexible and robust
  - [x] allow the config to appear spread out across several lines if one so pleases
  - [x] instead of passing everything from the second argument onward to `lushui`, introduce some indirection like `compiler-flags …` and `runtime-flags …`
