### ISSUE TITLE
Improve golden tester

### ISSUE THREAD

**Issue by fmease** [fmease/lushui#19]
- [x] Print file diffs instead of both golden and actual output. Use the crate [difference](https://crates.io/crates/difference) for this. Right now, the differences are really hard to spot.
- [x] Compile the lushui compiler before running the tests (via `cargo run`). This already lead to several bugs (setting up CI) and frustrating debugging sessions. Update CI once this task is completed
- [x] Don't hackily invoke the compiler by referencing the `target` directory but get the information from `cargo` (smh). This ensures compatibility with Windows
- [x] Allow passing environment variables to overwrite/update certain (or all) golden files
- [ ] Improve error reporting
- [x] Add support for (nested) folders in `tests/` so we can start organizing tests by topic, domain etc. and feel more motivated to write more tests
