### ISSUE TITLE
Move golden testing out of Cargo test infrastructure

### ISSUE THREAD

**Issue by fmease** [fmease/lushui#77]
The current system is not flexible and not refined/impeccable/polished. We'd like to exclude golden testing in some scenarios and
include it in others. Further, this system is a bit hacky in that it launches the golden tester – a testing framework on its own – through a Cargo "unit test". This means the golden tester is constrained by the Cargo testing framework. Most notably, its output is buffered and not shown by default. Further, configurations needs to be passed as environment variables. All that is not ideal. As a result, the golden testing framework does not appear as professional as it could.

- [x] make the golden testing framework standalone by moving it to a new rust binary
  - [x] do not crash on invalid header but treat those tests as a new category ("invalid")
  - [x] improve the output
  - [x] run the compiler in parallel and have a command line option ~~`--jobs`~~ `--test-threads` for the number of threads
  - [x] replace env var `GILD_ALL_FAILING` with command line flag `--gild`
  - [x] implement test filtering
- [x] create a rust or shell script to invoke both the Cargo testing framework and the golden testing framework
- [x] register the now separate golden tester as GitHub action
